baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Shergill & Co. - Solicitors and Notary Public'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  address: '<a class="zerostatic" href="https://goo.gl/maps/q8ARQSHTwQwMR3RNA" 22 Bath Road, Hounslow, TW3 3EB</a>'
  phone: '<a class="zerostatic" href="https://goo.gl/maps/q8ARQSHTwQwMR3RNA"  020 8570 2323</a>'
  fax: '<a class="zerostatic" href="https://goo.gl/maps/q8ARQSHTwQwMR3RNA" 0845 0176795 DX345 HOUNSLOW</a>'

seo:
  meta_og_title: 'Shergill & Co. - Solicitors and Notary Public'
  meta_og_type: "website"
  meta_og_url: "https://jekyll-serif-theme.netlify.app"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Jekyll Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_twitter_card: "summary"
  meta_twitter_site: "@zerostaticio"
  meta_twitter_creator: "@zerostaticio"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
